# Use an official Node runtime as a parent image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to leverage Docker cache
COPY package.json package-lock.json ./

# Install application dependencies
RUN npm install

# Copy the rest of the application source code into the container
COPY . .

# The React development server runs on port 3000
EXPOSE 3000

# Command to run the development server
CMD ["npm", "start"]
